name: Build Chrome Extension

on:
  push:
    tags:
      - 'v*' # 当推送版本标签时触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        
    - name: Create extension package
      env:
        EXTENSION_KEY: ${{ secrets.EXTENSION_KEY }}
      run: |
        # 创建临时key文件
        echo "$EXTENSION_KEY" > key.pem
        
        # 首先创建zip包
        zip -r extension.zip . -x "*.git*" -x "*.github*" -x "*.zip" -x "*.crx" -x "key.pem"
        
        # 使用Chrome打包扩展
        chromium-browser --pack-extension=./ --pack-extension-key=key.pem
        
        # 删除临时key文件
        rm key.pem
        
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.crx
          extension.zip
        name: Release ${{ github.ref_name }}
        body: |
          Chrome Extension Release ${{ github.ref_name }}
          
          This release contains:
          - sp_cnki.crx: Signed Chrome extension package
          - extension.zip: Source files for manual installation
        draft: false
        prerelease: false
