name: Build Chrome Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Create extension package
      run: |
        # 创建发布目录
        mkdir -p dist
        
        # 复制必要文件到发布目录
        cp manifest.json content.js background.js icon48.png icon128.png dist/
        
        # 创建zip包
        cd dist
        zip -r ../sp_cnki.zip *
        cd ..
        
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        files: sp_cnki.zip
        name: Release ${{ github.ref_name }}
        body: |
          Chrome Extension Release ${{ github.ref_name }}
          
          This release contains the Chrome extension package ready for installation.
          
          Installation Steps:
          1. Download sp_cnki.zip
          2. Extract the zip file
          3. Open Chrome and go to chrome://extensions/
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
        draft: false
        prerelease: false
